function visitObj($container, obj) {
    var $ul = $('<ul>');

    for (var prop in obj) {

        var $li = $('<li>');
        $li.append('<span class="json-key">' + prop + ': </span>');
        if (typeof obj[prop] === "object") {
            visitObj($li, obj[prop]);
        } else {
            $li.append('<span class="json-value">'+obj[prop]+'</span>');                   
        }
        $ul.append($li);
    }
    $container.append($ul);
}

visitObj($('#display_pane'), {
       "Chariots of Fire":"https://www.youtube.com/watch?v=CwzjlmBLfrQ"
    , "A, Masliakov? ":"http://www.youtube.com/watch?v=PRm4N5CcZMY"
    , "Ain`t Nobody Got Time For That ":"http://www.youtube.com/watch?v=8cT_Ulmcrys"
    , "All is lost! ":"http://www.youtube.com/watch?v=EmJdZ7DcV7U"
    , "Atkinson & E.John ":"https://www.youtube.com/watch?v=Hm5EkJXlgM8"
    , "Baby Talk ":"http://www.youtube.com/watch?v=sDocL7AfIRo"
    , "Batman Chooses his voice ":"http://www.youtube.com/watch?v=WOg3ZE3hNQc"
    , "Bed Intruder ":"http://www.youtube.com/watch?v=VKsVSBhSwJg"
    , "Bilan Parody 1":"https://www.youtube.com/watch?v=rfXdRoUVUYo"
    , "Bilan Parody 2":"https://www.youtube.com/watch?v=xGIbMPSMFP8"
    , "Bolsheviks & Illiteracy":"http://www.youtube.com/watch?v=CX_S1DXHW4Y"
    , "Borsch ":"https://www.youtube.com/watch?v=cMIHLzuJ4Wg"
    , "Cause I`m drunk":"http://www.youtube.com/watch?v=Vw4_pwIUMPY"
    , "Celebration ":"https://www.youtube.com/watch?v=G7fo1hJIj5Y"
    , "Chinese Boso":"https://www.youtube.com/watch?v=hBxqptNa6-8"
    , "Chocolate waffles":"http://www.youtube.com/watch?v=eFcWvCEe0Ac"
    , "Coliseum":"https://www.youtube.com/watch?v=ftWL_ETjuo0"
    , "Couch":"http://www.youtube.com/watch?v=6Pm3KQvYk9Q"
    , "Crusty, Ted":"https://www.youtube.com/watch?v=BEKuKD4R0y4&list=UU2nPLKT5yMdVB5HoBpxRs8g"
    , "Cyborgs":"http://www.youtube.com/watch?v=1yjjNiu4i3k"
    , "Be Quiet":"http://www.youtube.com/watch?v=xpovtaBBLCE"
    , "L`on`a Killer":"http://www.youtube.com/watch?v=3EM4IyBlOzg"
    , "Pechen`ka":"http://www.youtube.com/watch?v=PvGRjauxf4M"
    , "Pechen`ye lom":"http://www.youtube.com/watch?v=2u-NHOGiiUw"
    , "Dudu":"http://www.youtube.com/watch?v=OLDGnawrdPk"
    , "Shito & Kryto":"http://www.youtube.com/watch?v=INBDbmDqZAg"
    , "Whack against the wall":"http://www.youtube.com/watch?v=GZBbtk47vZw"
    , "Do you speak English":"http://www.youtube.com/watch?v=rxUm-2x-2dM"
    , "Dramatic Animals ":"http://www.youtube.com/watch?v=0vT0dgIZN1o"
    , "Dramatic Cat ":"http://www.youtube.com/watch?v=plWnm7UpsXk"
    , "Dramatic Cat ":"http://www.youtube.com/watch?v=EmeLlUmg7Xc"
    , "Dramatic Gopher ":"http://www.youtube.com/watch?v=8lXdyD2Yzls"
    , "Dreyfuss reads EULA": "http://www.youtube.com/watch?v=Cu0lqUlHEko"
    , "Exam Answer Best ":"https://www.youtube.com/watch?v=cMsxnDMBifk"
    , "Frankenthumb" : "http://www.youtube.com/watch?v=TDYzLJk36VI"
    , "Gerald the Gorilla":"http://www.youtube.com/watch?v=beCYGm1vMJ0"
    , "German Coast Guard":"http://www.youtube.com/watch?v=yR0lWICH3rY"
    , "Give me the meat!":"https://www.youtube.com/watch?v=G1bziMXs_hs"
    , "Greatest Song in the World":"http://www.youtube.com/watch?v=_lK4cX5xGiQ"
    , "Guest on the treshhold":"http://www.youtube.com/watch?v=ViD4OBWt2EI"
    , "Gut":"http://www.youtube.com/watch?v=gUXSut1Y6VE"
    , "Hare poem (pole chudes" : "http://www.youtube.com/watch?v=O_Lu9MBqvak"
      , "Harbin Invitation":"http://www.youtube.com/watch?v=gJg9AR8p_qY"
      , "Hercules":"http://www.youtube.com/watch?v=8jRuK5mx9nA"
      , "History Lesson":"http://www.youtube.com/watch?v=YnFU22znYaM"
      , "History of English":"http://www.youtube.com/watch?feature=player_embedded&v=H3r9bOkYW9s"
      , "History Lesson":"http://www.youtube.com/watch?v=YnFU22znYaM"
      , "I`m So Excited":"http://www.youtube.com/watch?v=-aS3yhRqllU"
      , "IK+":"https://www.youtube.com/watch?v=wDko0WVJUr0"
      , "Imbecil":"http://www.youtube.com/watch?v=pwtU8ycIV5Y"
      , "Instant Noodles":"http://www.youtube.com/watch?v=BIDGPWAuvb4"
      , "Internets":"http://www.youtube.com/watch?v=LKTH6f1JfX8"
      , "Iron Mask, the":"http://www.youtube.com/watch?v=J398esfj5q8"
      , "Is There God":"http://www.youtube.com/watch?feature=player_embedded&v=A0g3uO1O3Lg"
      , "JK Wedding Dance":"http://www.youtube.com/watch?v=4-94JhLEiN0"
      , "Kenlee" : "https://www.youtube.com/watch?v=FQt-h753jHI"
      , "Kin-dza-dza Matrix":"http://www.youtube.com/watch?v=aTDliqQpdcU"
      , "Kin-dza-dza Terminator ":"http://www.youtube.com/watch?v=NZkPKKudfqI"
      , "KVN Best":"http://kvnbest.ru/"
      , "Lack of Evidence":"http://www.youtube.com/watch?v=lSqRGkDe6Dw"
      , "Latin":"https://www.youtube.com/watch?v=NI8UZubOJlo"
      , "Lada Priora":"http://www.youtube.com/watch?v=ybzymcQlozA&NR=1&feature=fvwp"
      , "Litvinkov":"https://www.youtube.com/watch?v=Yo4q89246dc"
      , "LOTR Remix 1":"https://www.youtube.com/watch?v=Q_Co7er4Vuk"
      , "LOTR Remix 2":"https://www.youtube.com/watch?v=rjx1-otbBLg"
      , "LOTR Remix 3":"https://www.youtube.com/watch?v=lTZw-WY4T10"
      , "Matrix Ukrainization":"http://www.youtube.com/watch?v=BZ70-zy9KZk"
      , "Medicinal grass from UZ" : "http://www.youtube.com/watch?v=SpdlG3IOQA4"
      , "Murmurs of the Middle Earth":"https://www.youtube.com/watch?v=XJfGnqKoXYY"
      , "My Heart Will Go On":"http://www.youtube.com/watch?v=tlDSsII-yBo"
      , "9gag":"http://9gag.com/"
      , "Novosib ozvuchka ":"http://www.youtube.com/watch?v=6w-PpPizmPk"
      , "Nucular ":"http://www.youtube.com/watch?v=OoASZyihalc"
      , "Offensive Translator":"http://www.youtube.com/watch?v=XY66ZJ0TFUI"
      , "OM* Cat ":"http://www.youtube.com/watch?v=C_S5cXbXe-41"
      , "Orders from Mordor ":"http://www.youtube.com/watch?v=fsXmG66ungE"
      , "Pelmeni Boyarskie ":"https://www.youtube.com/watch?v=yb2dZ_7jsco"
      , "Physics exam ":"https://www.youtube.com/watch?v=rpuXiZxZcog"
      , "Pickpocket Master ":"http://www.youtube.com/watch?v=0TOFlb09Vuk"
      , "Pillow Talk ":"http://www.youtube.com/watch?v=SERiABqsmyA"
      , "Reaction gifs":"http://www.reactiongifs.com/"
      , "Revva the Only Member":"http://www.youtube.com/watch?v=ILTriIzFye0"
      , "Riders on White Horses":"http://www.youtube.com/watch?v=XVsIeZW3OFU"
      , "Rocky Lockridge":"http://www.youtube.com/watch?v=mpDoziF-kyI"
      , "RU Help US after collapse ":"http://www.youtube.com/watch?v=KPaVRCpFL7g"
      , "Scaredy Guy ":"http://www.youtube.com/watch?feature=player_embedded&v=Bwr4XEHmfBs"
      , "Scwarzenegger Quotes ":"http://www.youtube.com/watch?v=pDxn0Xfqkgw"
      , "Soul on fire":"http://www.youtube.com/watch?v=EZ5SwfAqkVg"
      , "Stalking Cat ":"http://www.youtube.com/watch?v=fzzjgBAaWZw"
      , "Strategic Seeds ":"https://www.youtube.com/watch?v=LmGo1w82IM8"
      , "Stuntman Ukrop 1":"http://www.youtube.com/watch?v=QwVVONOn8JA"
      , "Stuntman Ukrop 2":"http://www.youtube.com/watch?v=vCUxgxgDvOE"
      , "Terminator in verse":"http://www.youtube.com/watch?v=oETUre2ey3A"
      , "Toilet Paper":"http://www.youtube.com/watch?v=uWdFHT4h29k"
      , "They`re taking the hobbits to Isengard ":"http://www.youtube.com/watch?v=uE-1RPDqJAY"
      , "Trial trial (channel)":"http://www.youtube.com/user/Trial1983?feature=watch"
      , "Turkish Action Movie":"http://www.youtube.com/watch?annotation_id=annotation_491226&feature=iv&src_vid=eECkdle_dTo&v=sPNYYr4aLaM"
      , "Twelve Chairs, the":"http://lib.ru/ILFPETROV/ilf_petrov_12_chairs_engl.txt"
      , "When I was little I had a grandma, too ":"http://www.youtube.com/watch?v=gffZRbGVJG4"
      , "Who Could Be President ":"http://www.youtube.com/watch?v=0SHsg20-9LM"
      , "Who farted?":"https://www.youtube.com/watch?v=78WEaRm2W2k"
      , "Why is the rum gone? ":"http://www.youtube.com/watch?v=JImcvtJzIK8"
    });